name: Daily Midnight Task

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 18:30 UTC (midnight IST)
  workflow_dispatch:      # Optional: allows manual trigger

jobs:
  function-calling:
    runs-on: ubuntu-latest

    steps:
      - name: Function Calling
        run: |
          curl -I "https://fxedtygfdamzhcaovesy.supabase.co/storage/v1/object/sign/initial-bucket/qr-code-for-gmail.png?token=${{ secrets.TOKEN }}"
